# /home/reeve/Vacuum_Cleaner_nav/src/vacuum_slam/config/ekf.yaml
# Configuration for robot_localization EKF node
ekf_filter_node:
  ros__parameters:
    frequency: 30.0                 # EKF 更新频率 (Hz)
    sensor_timeout: 0.1             # 传感器数据超时时间 (秒)
    two_d_mode: true                # 启用2D模式 (忽略Z轴、roll、pitch)

    # --- 坐标系 ---
    map_frame: map                  # 地图坐标系 (通常由SLAM发布)
    odom_frame: odom                # 里程计坐标系 (EKF输出的坐标系)
    base_link_frame: base_link      # 机器人基座坐标系
    world_frame: odom               # EKF状态估计参考的世界坐标系 (设为odom实现连续运动估计)

    # --- 传感器输入 ---

    # 输入1: 来自 laser_scan_matcher 的里程计 (轻量级解决方案)
    odom0: /laser_scan_matcher/odom # 激光扫描匹配器里程计话题
    odom0_config: [true,  true,  false,  # 融合 X, Y 位置
                   false, false, true,   # 融合 Yaw 角度
                   true,  true,  false,  # 融合 X, Y 方向线速度
                   false, false, true,   # 融合 Z 方向角速度
                   false, false, false]  # 不融合加速度
    odom0_queue_size: 10
    odom0_nodelay: false
    odom0_differential: false       # 如果odom发布的是位姿变化量而非绝对位姿，设为true
    odom0_relative: false           # 同上
    odom0_pose_rejection_threshold: 5.0    # 位姿拒绝阈值
    odom0_twist_rejection_threshold: 1.0   # 速度拒绝阈值

    # 输入2: 来自 IMU 的数据
    imu0: /imu/data                 # IMU数据话题
    imu0_config: [false, false, false,   # 不直接融合IMU的绝对Roll, Pitch, Yaw (避免漂移和跳变)
                  false, false, true,    # 融合 Yaw 角度 (使用IMU的偏航角)
                  false, false, false,   # 不融合 X, Y 方向线速度 (IMU不提供此信息)
                  false, false, true,    # 融合 Z 方向角速度 (使用IMU的角速度)
                  true,  false, false]   # 融合 X 方向线性加速度 (使用IMU的x轴加速度)
    imu0_nodelay: false
    imu0_differential: false        # IMU通常发布绝对姿态，所以设为false
    imu0_relative: false            # 同上
    imu0_queue_size: 10
    imu0_pose_rejection_threshold: 0.8                 # 位姿拒绝阈值
    imu0_twist_rejection_threshold: 0.8                # 速度拒绝阈值
    imu0_linear_acceleration_rejection_threshold: 0.8  # 加速度拒绝阈值
    imu0_remove_gravitational_acceleration: true       # 移除重力加速度影响

    # --- 输出 ---
    publish_tf: true                # EKF 是否发布 odom -> base_link 的TF变换
    publish_acceleration: false     # 是否发布加速度估计

    # --- 过程噪声协方差 (Process Noise Covariance) ---
    # 这些值表示对模型预测的不确定性，需要根据实际情况调整
    # 每个参数代表状态变量：(X, Y, Z, roll, pitch, yaw, Vx, Vy, Vz, Vroll, Vpitch, Vyaw, Ax, Ay, Az)
    process_noise_covariance: [0.05, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0.05, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0.06, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0.03, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0.03, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0.06, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0.025, 0,     0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0.025, 0,    0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0.04, 0,    0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,    0.01, 0,    0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.01, 0,    0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.02, 0,    0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.01, 0,    0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.01, 0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.015]

    # --- 初始状态协方差 (Initial Estimate Covariance) ---
    # 对初始状态的不确定性，对角线上的小值表示初始状态比较确定
    initial_estimate_covariance: [1.0e-9, 0,      0,      0,    0,    0,      0,     0,     0,      0,    0,    0,    0,    0,    0,
                                  0,      1.0e-9, 0,      0,    0,    0,      0,     0,     0,      0,    0,    0,    0,    0,    0,
                                  0,      0,      1.0e-9, 0,    0,    0,      0,     0,     0,      0,    0,    0,    0,    0,    0,
                                  0,      0,      0,      1.0,  0,    0,      0,     0,     0,      0,    0,    0,    0,    0,    0,
                                  0,      0,      0,      0,    1.0,  0,      0,     0,     0,      0,    0,    0,    0,    0,    0,
                                  0,      0,      0,      0,    0,    1.0e-9, 0,     0,     0,      0,    0,    0,    0,    0,    0,
                                  0,      0,      0,      0,    0,    0,      1.0,   0,     0,      0,    0,    0,    0,    0,    0,
                                  0,      0,      0,      0,    0,    0,      0,     1.0,   0,      0,    0,    0,    0,    0,    0,
                                  0,      0,      0,      0,    0,    0,      0,     0,     1.0e-9, 0,    0,    0,    0,    0,    0,
                                  0,      0,      0,      0,    0,    0,      0,     0,     0,      1.0,  0,    0,    0,    0,    0,
                                  0,      0,      0,      0,    0,    0,      0,     0,     0,      0,    1.0,  0,    0,    0,    0,
                                  0,      0,      0,      0,    0,    0,      0,     0,     0,      0,    0,    1.0,  0,    0,    0,
                                  0,      0,      0,      0,    0,    0,      0,     0,     0,      0,    0,    0,    1.0,  0,    0,
                                  0,      0,      0,      0,    0,    0,      0,     0,     0,      0,    0,    0,    0,    1.0,  0,
                                  0,      0,      0,      0,    0,    0,      0,     0,     0,      0,    0,    0,    0,    0,    1.0]
