# Configuration for slam_toolbox (async mode)
# See https://github.com/SteveMacenski/slam_toolbox/blob/ros2/config/mapper_params_online_async.yaml

slam_toolbox:
  ros__parameters:
    # Required Parameters
    odom_frame: odom          # Odometry frame (from EKF)
    map_frame: map            # Map frame (published by slam_toolbox)
    base_frame: base_link     # Robot base frame
    scan_topic: /scan         # Laser scan topic

    # Use scan matching results for odometry? Set to false if using fused odom from robot_localization
    use_scan_matching: false

    # Use IMU data? Set to false as we are using fused odometry from EKF
    use_imu_data: false

    # Use odometry data from tf? Set to true to use the odom->base_link transform from EKF
    use_odom_tf: true

    # Mode: mapping or localization
    mode: mapping             # Start in mapping mode

    # General Parameters
    resolution: 0.05          # Map resolution (meters/pixel)
    map_update_interval: 5.0  # Update map interval (seconds)
    max_laser_range: 25.0      # Max laser range to consider (meters) - Adjust based on your lidar
    minimum_time_interval: 0.2 # Minimum time interval between scans (seconds)
    transform_timeout: 0.2    # TF timeout (seconds)
    tf_buffer_duration: 30.0  # TF buffer duration (seconds)

    # Scan Matcher Parameters (Used if use_scan_matching is true, but good to have defaults)
    matcher_iterations: 10
    matcher_maximum_iterations: 10 # Deprecated, use matcher_iterations
    matcher_maximum_distance: 0.2
    matcher_translation_weight: 2.0
    matcher_rotation_weight: 1.0
    # ... other matcher parameters can be added if needed

    # Loop Closure Parameters
    do_loop_closing: true
    loop_match_minimum_response_fine: 0.6
    loop_match_maximum_distance: 10.0
    # ... other loop closure parameters

    # Map Parameters
    map_start_at_dock: false # If you have a dock pose

    # Other settings
    debug_logging: false
    throttle_scans: 1         # Process every N scans
    use_map_saver: true       # Enable map saving service
    map_file_name: "saved_map" # Default name for saved map
    map_save_duration: 60.0   # Auto-save interval (seconds), 0 to disable

    # Consider adding parameters related to your specific lidar and environment
    # e.g., min_laser_range, erosion_radius, etc.
