# /home/reeve/Vacuum_Cleaner_nav/src/vacuum_slam/config/mapper_params_online_async.yaml
slam_toolbox:
  ros__parameters:
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: HuberLoss

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    # Use scan_matching to improve odometry drift correction (requires more CPU)
    use_scan_matching: true
    # Lower means higher resolution
    resolution: 0.05
    # Maximum laser range to use for map building
    max_laser_range: 8.0 # Adjust based on your lidar spec (e.g., LD14 is typically 8m or 12m)
    # Minimum laser range to use for map building
    min_laser_range: 0.1 # Adjust based on your lidar spec
    # Minimum scan range angle (radians)
    minimum_scan_range: -2.35619 # -135 degrees
    # Maximum scan range angle (radians)
    maximum_scan_range: 2.35619  # +135 degrees
    map_update_interval: 1.0 # Update map every 1 second
    # Transform tolerance in seconds
    transform_publish_period: 0.02 # ~50Hz
    tf_buffer_duration: 30.0 # seconds

    # General tuning parameters
    # Threshold for loop closure score
    loop_search_maximum_distance: 10.0
    # Minimum score for accepting loop closure using scan matching
    minimum_scan_match_score: 0.4
    # Number of scans to use for matching
    correlation_scan_match_resolution: 0.1
    # Distance threshold for loop closure search
    loop_match_minimum_response_fine: 0.6
    # Distance threshold for loop closure search
    loop_match_maximum_distance: 2.0

    # Other parameters... (refer to slam_toolbox documentation for more)
    mode: mapping # or localization
